version: "3.8"
services:
  picoshare:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: picoshare
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - PS_SHARED_SECRET=123456 # Cambia este valor en producción
    command: -db /data/store.db
    volumes:
      - ./data:/data
    restart: unless-stopped
